Added a Questions- and Eventshandler
hfxbse/mparty pull request #2
Opened 2023-05-22 14:03 UTC by KevinBasener

Creating the necessary objects for the Questions- and EventsHandler. The questions and the events are read from a json file. The two handler then provide useful methods to utilize the questions and events.

2023-05-22 16:05 UTC, hfxbse requested changes

2023-05-22 16:05 UTC, hfxbse commented on Scripts/model/event.gd
Do not create getters and setters like this. There is no concept of private class members in GDScript, just access them directly without any unnecessary boilerplate. 

Only if you need to validate something when accessing or assigning a variable, you should set [getters or setters on the property directly](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#properties-setters-and-getters).

2023-05-22 16:05 UTC, hfxbse commented on Scripts/data_handler/events_handler.gd
Shouldn't the EventHandler conceptional extend from JsonLoader instead of instantiating it?

I'm also not sure about the "Handler"-Part of the name, as it does not actually perform any event, therefore does not handle an event. It does provide an Event, so I would think "EventProvider" would be a more fitting name.

2023-05-22 16:05 UTC, hfxbse commented on Scripts/data_handler/json_loader.gd
It would be probably better to try opening the file, then check if the return value is null to see if it failed. Just because the file does exists doesn't mean it can be read. This seems safer then trying to call `get_as_text()` on null potentially.

2023-05-22 16:05 UTC, hfxbse commented on Scripts/data_handler/quesions_handler.gd
Making the question difficulty type an enum seems to be more fitting

2023-05-22 16:05 UTC, hfxbse commented on Scripts/data_handler/events_handler.gd
Not sure if swallowing the out of bound access is the best idea. If you don't swallow it, by default, it will print an error message and halt the execution when run in the editor.
Also, negative indices are allowed in GDScript an will behave just like in Python.

If you want to go this route, at least remove the code duplication between the EventHandler and QuestionHandler

2023-05-22 16:05 UTC, hfxbse commented on Scripts/data_handler/events_handler.gd
Printing a error to stdout, not even stderr, as only error handling seems questionable. There is an [`assert` function](https://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-method-assert) which should handle most of the stuff. If something can fail silently, it at least should also be written to stderr imo.

2023-05-22 16:05 UTC, hfxbse commented on Scripts/model/event_battle.gd
Line 12 can never be reached. It should be possible to return multiple values as tuple just like in python, but it won't be needed here as far as I'm aware as unnecessary getters and setters should be removed anyways.

2023-05-22 16:05 UTC, hfxbse commented on Scripts/model/event.gd
As far as I'm aware it is not yet decided if a event will ever have a question, and as not all events will have a question, it seems misplaced in the parent class

2023-05-22 16:05 UTC, hfxbse commented on Scripts/model/player.gd
Different concern, should be in a separate PR

2023-05-22 16:05 UTC, hfxbse commented on Scripts/model/question.gd
The method `set_answer_possibilities` has "set" in the name but actually appends the questions. As mentioned before, there is no need for setters and getters, therefore it is probably best to remove it all together. If someone needs to append an array they should call the `+`-operator on the field instead

2023-05-22 16:05 UTC, hfxbse commented on node_2d.tscn
Not sure what this file does as the name does not tell me anything of relevance. I assume this is just an empty scene for testing purposes? It at least seems like it

2023-05-22 16:05 UTC, hfxbse commented on Scripts/model/question.gd
The difficulty may be an enum type instead as well

2023-05-22 16:05 UTC, hfxbse commented on Scripts/model/event.gd
I would prefer to not merge a TODO in the main branch, especially if the design decision how to handle this use-case is well defined.

2023-05-22 16:05 UTC, hfxbse commented on Scripts/main.gd
using `preload` instead of `load` seems fitting here

2023-05-22 16:05 UTC, hfxbse commented on Scripts/data/events.json
I would love an explanation on how to initiate different types of events from the JSON file. My guess is, that it is relying on predefined types, which might be influenced by some variables in the JSON file.

It would be nice to either demonstrate the concept already or remove it till it is more clear. As for now, only the base event type is used and the other types are death code.

2023-05-24 19:14 UTC, hfxbse requested changes
Much cleaner, I like it besides a few minor improvement opportunities :)

2023-05-24 19:14 UTC, hfxbse commented on scripts/data_provider/quesions_provider.gd
To create a copy of the array you can simply use the [`duplicate` method](https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-duplicate), no need to loop over them individually.

2023-05-24 19:14 UTC, hfxbse commented on scripts/data_provider/quesions_provider.gd
Mapping the difficulty to the enum can be done via a dictionary, where the key is the value saved in the JSON file, and the corresponding value is the enum value. This would be a more scalable approach.

```GDscript
const difficultiyMapping = {
    "0": EASY,
    "1": NORMAL,
    "2": DIFFICULT
}

const difficulty = difficultiyMapping[question["difficulty"]]
assert(difficulty != null, "Difficulty \"%s\" not supported." % question["difficulty"])
```

2023-05-24 19:14 UTC, hfxbse commented on scripts/data_provider/json_loader.gd
The second check if the file could be open should be sufficient, no need to check if the file exists beforehand.
Adding the file path to the error message would be nice, a [format String](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_format_string.html) can be used for this :)

2023-05-24 19:14 UTC, hfxbse commented on Scripts/model/question.gd
> The difficulty may be an enum type instead as well

Using the same enum as in `QuestionProvider` seems to be fitting

2023-05-24 19:14 UTC, hfxbse commented on addons/godot-git-plugin/win64/libgit_plugin.windows.editor.x86_64.dll
Not sure how I feel about adding add-ons not existential to the project to the repository, IMO there should be a team decision on how we do this.

2023-05-25 05:20 UTC, KevinBasener commented on addons/godot-git-plugin/win64/libgit_plugin.windows.editor.x86_64.dll
Didn't know how that thing got in, I haven't installed it intentionally and will get rid of it.

2023-05-25 06:05 UTC, KevinBasener commented on scripts/data_provider/quesions_provider.gd
> To create a copy of the array you can simply use the [`duplicate` method](https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-duplicate), no need to loop over them individually.

If you refer to the extra looping for answer_possibilities, I decided to loop over it so I can make sure the array will be of type Array[String], because it won't be of that type if I've only assigned it to the variable. Maybe this is due to the json_loader using the get_as_text() method.

2023-05-25 06:10 UTC, KevinBasener commented on Scripts/model/question.gd
As far as I know I can't say something like var question: enum in GDScript. But int seems to work fine.

2023-05-25 06:12 UTC, KevinBasener commented on scripts/data_provider/quesions_provider.gd
I like that mapping approach, much more flexible.

2023-05-25 06:41 UTC, hfxbse commented on Scripts/model/question.gd
You can, but you need to give the enum a name like this:
```GDScript
class_name Question

enum Difficulty {EASY, NORMAL, DIFFICULT}

var question: String
var answer_possibilities: Array[String]
var right_answer: int
var difficulty: Difficulty
```

To make use of it in other parts of the project you access it through the class name like this:
```GDScript
const difficulty_mapping = {
	"0": Question.Difficulty.EASY,
	"1": Question.Difficulty.NORMAL,
	"2": Question.Difficulty.DIFFICULT
}

var questions = {
	Question.Difficulty.EASY: [], 
	Question.Difficulty.NORMAL: [], 
	Question.Difficulty.DIFFICULT: []
}
```
Casting it to an `int` probably works due to how they are implemented in GDScript, but I don't know exactly.

2023-05-25 06:55 UTC, hfxbse commented on scripts/data_provider/quesions_provider.gd
> > To create a copy of the array you can simply use the [`duplicate` method](https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-duplicate), no need to loop over them individually.
> 
> If you refer to the extra looping for answer_possibilities, I decided to loop over it so I can make sure the array will be of type Array[String], because it won't be of that type if I've only assigned it to the variable. Maybe this is due to the json_loader using the get_as_text() method.

I see. There is a [`assign` method](https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-assign) that will handle the type conversion for you.

After reordering the code a little bit it could look like this:
```GDScript
for question in questions_from_json:
	var difficulty = difficulty_mapping[str(question["difficulty"])]
	(difficulty != null, "Difficulty \"%s\" is not supported." % difficulty)
		
	question_obj = Question.new()
	question_obj.question = question["question"]
	question_obj.answer_possibilities.assign(question["answer_possibilities"])
	question_obj.right_answer = question["right_answer"]
	question_obj.difficulty = difficulty
		
	questions[difficulty].append(question_obj)
```

2023-05-25 07:01 UTC, hfxbse commented
I just noticed you named one directory `Scripts` and the other one `scripts`. Capitalization does matter on most systems so this is an actual issue. Based on your code, it should be all lowercase both times.

2023-05-25 08:12 UTC, KevinBasener commented on scripts/data_provider/json_loader.gd
Isn't that already implmented?

2023-05-25 08:13 UTC, hfxbse commented on scripts/data_provider/json_loader.gd
The second error message should also include the file path imo

2023-05-25 13:33 UTC, KevinBasener commented on scripts/data_provider/json_loader.gd
True lol, didn't noticed

2023-05-25 13:39 UTC, hfxbse commented
> I just noticed you named one directory `Scripts` and the other one `scripts`. Capitalization does matter on most systems so this is an actual issue. Based on your code, it should be all lowercase both times.

You need to also move the actual files to the `scripts` directory. After that I'll merge it :)

2023-05-27 08:21 UTC, KevinBasener commented
> > I just noticed you named one directory `Scripts` and the other one `scripts`. Capitalization does matter on most systems so this is an actual issue. Based on your code, it should be all lowercase both times.
> 
> You need to also move the actual files to the `scripts` directory. After that I'll merge it :)

Should be done

2023-05-28 10:51 UTC, hfxbse approved these changes

2023-05-28 10:52 UTC, merged