Dice
hfxbse/mparty pull request #29
Opened 2023-07-10 19:06 UTC by grxver7

Adding Dice Scene to main. 

#CanvasLayer
#Centered
#No animations, causing issues

2023-07-10 20:47 UTC, ubeF requested changes
Remove

2023-07-10 22:48 UTC, ubeF approved these changes, later dismissed

2023-07-11 01:01 UTC, hfxbse requested changes
Looks good so far. All that is left to do is to add a coroutine that shows the dialog and returns the dice result. The idea is to [call and await the coroutine in the main loop](https://github.com/hfxbse/mparty/blob/a35bc6fcc572574d37810c52c1401e03263e8422/main/main.gd#L84).

2023-07-11 01:01 UTC, hfxbse commented on dice/Dice.gd
> +	self.visible = false
No need to prefix `visible` with `self`.

2023-07-11 09:50 UTC, KevinBasener commented on dice/Dice.gd
> +	self.visible = false
Connected the dice menu to the player movement in main.

2023-07-11 10:17 UTC, hfxbse reviewed
Not really a fan of adding a scene to instantiate the dice scene, which seems overly complicated. The wording `add_dice_menu` also does give any indication that it is performing the dice roll at all. Why not instantiate the scene directly and await the signal afterward, then clean up?

The files within `dice` should also be renamed to start with a lowercase letter.

2023-07-11 10:17 UTC, hfxbse commented on menu_overlay/menu_overlay.gd
> +	await get_tree().create_timer(1.5).timeout
Kinda a weird feeling having an additional delay after the dice interface disappears.

2023-07-11 10:47 UTC, KevinBasener commented
> Not really a fan of adding a scene to instantiate the dice scene, which seems overly complicated. The wording `add_dice_menu` also does give any indication that it is performing the dice roll at all. Why not instantiate the scene directly and await the signal afterward, then cleaning up?
> 
> The files within `dice` should also be renamed to start with a lowercase letter.

The idea was to have an extra layer other than hud, to display all the dialogs that might be added. Therefore keeping the hud elements and dialogs on seperate layers. Should I instead add the dice to hud or even directly to the main tree?

2023-07-11 11:01 UTC, hfxbse commented
> > Not really a fan of adding a scene to instantiate the dice scene, which seems overly complicated. The wording `add_dice_menu` also does give any indication that it is performing the dice roll at all. Why not instantiate the scene directly and await the signal afterward, then clean up?
> > The files within `dice` should also be renamed to start with a lowercase letter.
> 
> The idea was to have an extra layer other than hud, to display all the dialogs that might be added. Therefore keeping the hud elements and dialogs on separate layers. Should I instead add the dice to the hud or even directly to the main tree?

Do not put it in the HUD, it is a dialog and has nothing to do with it. Just keep it as simple as possible and insert it directly into the main tree. I do not see how an extra layer would add any real value, as that layer needs to be added a different sub-trees if implemented, but not every sub-tree needs for example the dice dialog.

2023-07-11 11:51 UTC, KevinBasener commented
> > > Not really a fan of adding a scene to instantiate the dice scene, which seems overly complicated. The wording `add_dice_menu` also does give any indication that it is performing the dice roll at all. Why not instantiate the scene directly and await the signal afterward, then clean up?
> > > The files within `dice` should also be renamed to start with a lowercase letter.
> > 
> > 
> > The idea was to have an extra layer other than hud, to display all the dialogs that might be added. Therefore keeping the hud elements and dialogs on separate layers. Should I instead add the dice to the hud or even directly to the main tree?
> 
> Do not put it in the HUD, it is a dialog and has nothing to do with it. Just keep it as simple as possible and insert it directly into the main tree. I do not see how an extra layer would add any real value, as that layer needs to be added a different sub-trees if implemented, but not every sub-tree needs for example the dice dialog.

Putting it directly into the main tree, leads to the problem, that the dice dialog behaves like the map when the main camera is used. It will stay at the same coordinates in the scene (like map), when the main camera is drag clicked, but it will not be at a fixed place (e.g. center) of the window.

2023-07-11 11:55 UTC, hfxbse commented
> Putting it directly into the main tree, leads to the problem, that the dice dialog behaves like the map when the main camera is used. It will stay at the same coordinates in the scene (like map), when the main camera is drag clicked, but it will not be at a fixed place (e.g. center) of the window.

Can this not be addressed by changing the root node of the dice panel scene to a canvas like it has been done in other scenes before?

2023-07-11 11:58 UTC, KevinBasener commented
> > Putting it directly into the main tree, leads to the problem, that the dice dialog behaves like the map when the main camera is used. It will stay at the same coordinates in the scene (like map), when the main camera is drag clicked, but it will not be at a fixed place (e.g. center) of the window.
> 
> Can this not be addressed by changing the root node of the dice panel scene to a canvas like it has been done in other scenes before?

Oh yes, true. Now its fixed.

2023-07-11 12:04 UTC, hfxbse approved these changes

2023-07-11 12:07 UTC, merged