Overlay
hfxbse/mparty pull request #31
Opened 2023-07-10 23:22 UTC by grxver7

2023-07-10 23:53 UTC, hfxbse requested changes
We do not need the generated template and comments from the engine. Please remove them where applicable.

Please follow our naming conversion for files. They should be in `snake_case`. A few of them deserve more descriptive names. For example, `grid_container.gd` could be called `stats_panel.gd` instead.

I am not sure why there are two different settings icons, either one might be left over. In addition, files for the patent view, the dice, and the start menu are in this branch, which should be a separate pull request. Most likely you need to drop f26dc37dda57e58c33684b37eacd867f2df4796b from your branch to get rid of most of them.

Something completely missing is a way to update the panels from the code. Please add methods to the scene which update them. The idea is to later call those from the main loop. In the main script are a few [method templates](https://github.com/hfxbse/mparty/blob/overlay/main/main.gd#L100C12-L100C12) for it already.

After this is done, I'll have a second look and hopefully, we can merge it finally after that :)

2023-07-10 23:53 UTC, hfxbse commented on main/main.gd
> +
Unnecessary whitespace.

2023-07-10 23:53 UTC, hfxbse commented on overlay/ActionMenue.gd
Empty file.

2023-07-11 00:01 UTC, hfxbse commented
Be aware that 7860cbb7a6a3bab9ee256079bd60c016c7f3e9d9 is a different commit than the commit in the main branch, which is 7366241371419430722022b63d70bd5c50579dab. Dropping the first one and rebasing on the latter one might be required.

2023-07-11 13:16 UTC, KevinBasener commented
Added methods to update the stats of hud and removed dice and patent view

2023-07-11 15:32 UTC, hfxbse requested changes, later dismissed
* It still does not indicate whose turn it is.
* There are also still two settings icon files. 
* As the patent view button does not do anything, remove it for now. 
* The round indicator should not show zero unless the game has not started yet.

Not all elements are properly aligned, but I can accept that for now.

2023-07-11 15:32 UTC, hfxbse commented on main/main.gd
> +
Unnecessary white space.

2023-07-11 18:00 UTC, grxver7 commented
Settings are removed
Patent view also

Players turn was colormarked in the stats menue. Someone removed it

2023-07-11 18:25 UTC, hfxbse commented
> Players turn was colormarked in the stats menue. Someone removed it

I know that it was at some point, but it is not now. Could you just add it in again?

2023-07-11 20:53 UTC, KevinBasener commented
> > Players turn was colormarked in the stats menue. Someone removed it
> 
> I know that it was at some point, but it is not now. Could you just add it in again?

Is fixed

2023-07-12 22:56 UTC, ubeF approved these changes

2023-07-12 22:59 UTC, merged