Sabotage dialog
hfxbse/mparty pull request #35
Opened 2023-07-12 16:56 UTC by grxver7

2023-07-12 23:43 UTC, ubeF commented
- The Description of the sabotage-events is dated ("Eigentor" is now only on 11 for example)
- Why does sabotage have it's own dice result instead of re-using the normal dice?
- It would probably be better to use the player-icons on the buttons instead of "a, b, c, d" so it's easier to pick the correct player

2023-07-13 17:54 UTC, grxver7 commented
Player selection: Player Icons sind eingesetzt. 

Dice result: Die Szene (ist vllt von der Namenskonvention nicht so gut) ist als Information für den Player gedacht. Dort soll als Labwel stehen, welche Sabotage nun erfolgt. Also zum Beispiel "Du erhältst eine Sabotage Freikarte".

2023-07-13 17:59 UTC, grxver7 commented
Würfelergebnisse wurden angepasst. Also 1-6 duell...

2023-07-13 20:07 UTC, ubeF commented
Window displaying the different options is displayed behind map

2023-07-13 20:40 UTC, ubeF commented
Following players should not be displayed in the "select_duellist" window:
- The player picking his opponent
- Players, which have the attribute "sabotage_card" set to true

2023-07-14 15:08 UTC, ubeF commented
"select_duelist" scene is for some reason invisible when instantiated

2023-07-15 14:15 UTC, ubeF commented
Basically completed. only waiting for merging of:
- [ ] #50 Target Selector
- [ ] #48 Duels

2023-07-16 08:12 UTC, hfxbse requested changes
Looks fine mostly so far.

2023-07-16 08:12 UTC, hfxbse commented on sabotage_field/sabotage_dice_result.gd
> +		result="Big Baller Duell Einsatz: halbes Vermögen"
The variable `result` is not declared in the current scope, seems to be a recent change that broke it.

2023-07-16 08:12 UTC, hfxbse commented on sabotage_field/sabotage_dice_result.gd
> +		action = duel_roll
Mapping the values should also be done with a Dictionary but at least use `elif` for consecutive statements.

2023-07-16 08:12 UTC, hfxbse commented on player/player.gd
> +				riesen = 0
cloud be one line with `riesen = max(0, amount)`.

2023-07-16 14:01 UTC, hfxbse requested changes
The directory `sabotage_field` should be called `sabotage_dialog` to not create confusion with the actual field for the map.

2023-07-16 14:01 UTC, hfxbse commented on sabotage_field/sabotage_dice_result.gd
> +	target -= bet_amount
This is not working. You probably meant
```gdscript
attacker.riesen += bet_amount
target.riesen -= bet_amount
```

2023-07-16 14:01 UTC, hfxbse commented on sabotage_field/sabotage_dice_result.gd
I would love to see the display options separated from the function as I did for the action dialog.

2023-07-16 14:01 UTC, hfxbse commented on sabotage_field/sabotage_dice_result.gd
> +@onready var label=$CanvasLayer/Panel/Label
The spaces between the equal sign are missing. It should be:
```gdscript
@onready var label = $CanvasLayer/Panel/Label
```

2023-07-16 14:01 UTC, hfxbse commented on project.godot
> +config/icon="res://player/icon.svg"
This icon is not present anymore, please revert the project file to the one in main.

2023-07-16 14:01 UTC, hfxbse commented on player/player.gd
> +			riesen = max(0, riesen)
Write it in one line instead.
```gdscript
riesen = max(0, amount)
```

2023-07-16 14:28 UTC, hfxbse approved these changes
I cannot be border to test it by getting lucky and landing on the matching field, but I do not see why it should not work now haha.

2023-07-16 14:30 UTC, merged