Add event provider
hfxbse/mparty pull request #46
Opened 2023-07-13 20:12 UTC by jujujuok

2023-07-14 09:23 UTC, KevinBasener commented
I would remove all sabotage and duel related functions and data in the event.json, because this will be handled, by other scripts (mostly what Felix did).

2023-07-14 14:05 UTC, ubeF commented on data_providers/data/events.json
> +    "textTwice": [
since "textTwice" won't be implemented please remove those actions

2023-07-14 14:19 UTC, ubeF requested changes
We don't need functions for getting specific event-types. Please implement a function which returns an event-object containing:
- the text
- the type-text (for example "textLost") or an enum, which represents them
- the number (for example: -200). If the event is not numerical set it to null

It's unnecessary to differentiate between "textGain" and "textLost". the difference is already reflected in the numbers

2023-07-14 14:41 UTC, hfxbse requested changes

2023-07-14 14:41 UTC, hfxbse commented on data_providers/data/events.json
The text values could already be a [Godot format string](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_format_string.html), no need to use `{0}` as a placeholder. It might be worth it to use it for every string and never write the value in it directly.

2023-07-14 14:41 UTC, hfxbse commented on data_providers/data/events.json
Why are the text-value relations an array instead of an object? It is error-prone to rely on the position to determine its usage. Texts with the same group could also be grouped, no need to repeat yourself every time.

2023-07-14 14:41 UTC, hfxbse commented on data_providers/event_provider.gd
Creating one function for each event type with an enum as a parameter to choose a variation would result in a less copy 'n paste-looking code.

2023-07-14 14:41 UTC, hfxbse commented on data_providers/event_provider.gd
> +# 	als liste zurück gegeben
Do not use any arry for this but its own event class. As a rule of thumb, if a caller has to look up what your function is returning and cannot guess it by the name, it sounds like a code smell.

_Also, the code language is English._

2023-07-14 14:41 UTC, hfxbse commented on data_providers/model/question.gd
> +var answer_possibilities: Array
Is this an intentional change?

2023-07-16 08:45 UTC, KevinBasener commented
Is this finished?

2023-07-16 10:44 UTC, hfxbse commented
These parts are currently not parsed into an event object:

```json
{
	"diceRoll": {
		"again": [...],
		"twice": [...]
	},
	"move": {
		"undo": [...],
		"start": [...]
	},
	"switch": {
	        ...
	},
 	"duel": {
		...
	},
	"steal": {
		...
	},
	"card": {
		...
	}
}
```
Not sure which are still required, but after everything is parsed, it should only be a matter of returning the right event as far as I am aware.

2023-07-16 11:53 UTC, KevinBasener commented
> These parts are currently not parsed into an event object:
> 
> ```json
> {
> 	"diceRoll": {
> 		"again": [...],
> 		"twice": [...]
> 	},
> 	"move": {
> 		"undo": [...],
> 		"start": [...]
> 	},
> 	"switch": {
> 	        ...
> 	},
>  	"duel": {
> 		...
> 	},
> 	"steal": {
> 		...
> 	},
> 	"card": {
> 		...
> 	}
> }
> ```
> 
> Not sure which are still required, but after everything is parsed, it should only be a matter of returning the right event as far as I am aware.

Added dice roll as well as the other movement events. Everything else shouldn't be needed according to the gameplan.

2023-07-16 12:08 UTC, ubeF commented
There is nothing implemented to support "texttwice" events. we should remove those

2023-07-16 12:37 UTC, KevinBasener commented
> There is nothing implemented to support "texttwice" events. we should remove those

You mean rollDice twice?

2023-07-16 12:39 UTC, ubeF commented
> > There is nothing implemented to support "texttwice" events. we should remove those
> 
> You mean rollDice twice?

yes

2023-07-16 13:05 UTC, KevinBasener commented
> > > There is nothing implemented to support "texttwice" events. we should remove those
> > 
> > 
> > You mean rollDice twice?
> 
> yes

Was removed

2023-07-16 15:29 UTC, hfxbse approved these changes

2023-07-16 15:37 UTC, ubeF approved these changes

2023-07-16 15:39 UTC, merged