Implement Duels
hfxbse/mparty pull request #48
Opened 2023-07-14 13:53 UTC by ubeF

Implement duel scene:
- Coroutine:
  - Params: two players - attacker and target
  - Return: signal, which resolves to either Win, Loss or Draw (use Enum)
- Use question difficulty dialog to get difficulty
- ask up to 3 questions
- every question has to be answered 2 times, once by each player
- display which player answers when
- only ask next question, if question before that was a draw
- if all 3 questions are draw return Draw
- announce result
- emit signal with result

2023-07-14 13:54 UTC, ubeF commented
Not sure if the files in duel/ are of any help, i just moved them here

2023-07-15 15:05 UTC, KevinBasener commented
Implemented requested features and added players name, so it is possible to differentiate whos turn it is.

2023-07-16 09:00 UTC, hfxbse requested changes
Gameplay-wise: Why not reveal the answer to the question after both players answered instead? Would be cool to show both logged-in answers on the same panel but I believe we have no time left to do so.

2023-07-16 09:00 UTC, hfxbse commented on main/main.gd
> +				player.player_name = "Dollar"
Creating an array for the names like it is done with the sprites seems more maintainable IMO.

2023-07-16 09:00 UTC, hfxbse commented on player/player.gd
> +			player.riesen -= pot
Not a fan of the match statement here. Why not do it like this to not repeat yourself?

```gdscript
# TODO: Add an early exit if it is possible to draw
var pot = self.riesen / 2

if result == dual_panel.DualEndings.ATTACKER_LOSES:
    pot *= -1

self.riesen += pot
player.riesen -= pot
```

As you have the same match statement further down in your code, create a separate function for it. Do not duplicate code. I image the function something like this:

```gdscript
func apply_dual_outcome(other_player: Player, bet_amount: int: result: DualEndings):
    ...
```

2023-07-16 09:00 UTC, hfxbse commented on player/player.gd
> +		duel_panel.DuelEndings.ATTACKER_WINS:
Might be worth it to access the enum through the class name instead of the instance.

2023-07-16 09:00 UTC, hfxbse commented on question_panel/answer_button.gd
Only made the formating worse, please revert it to the version in main.

2023-07-16 09:00 UTC, hfxbse commented on question_panel/question_panel.gd
> +
Unnecessary tab.

2023-07-16 09:00 UTC, hfxbse commented on question_panel/question_panel.gd
> +		if question_label:
You should also check if the value is actually different than the previous one.

2023-07-16 09:00 UTC, hfxbse commented on question_panel/question_panel.gd
> +		var answer_button = create_answer_button(answer_possibility, _on_answer_selected)
Not really related to this PR, but IMO you should not be forced to add a receiver to the button during the creation. Just add it directly on it in a second line.

```gdscript
var answer_button = create_answer_button(answer_possibility)
answer_button.connect(_on_answer_selected)
```

2023-07-16 09:00 UTC, hfxbse commented on question_panel/question_panel.gd
> +	var question_handler = preload("res://data_providers/question_provider/question_provider.tres")
The variable `question_handler`, which should be called `question_provider` in the first place, is never used. This smells like copy 'n pasta, which it is actually.

Convert it to this instead:
```gdscript
func display_question(difficulty: Question.Difficulty):
	var question_handler = preload("res://data_providers/question_provider/question_provider.tres")
	display_specific_question(question_handler.get_random_question(difficulty))

func display_specific_question(question: Question):
    ...
```

2023-07-16 10:10 UTC, KevinBasener commented
All issues adressed

2023-07-16 10:21 UTC, ubeF commented on player/player.gd
> +			player.riesen -= pot
What about a draw. In that case nothing is supposed to happen

2023-07-16 12:28 UTC, closed without merging