Target Selector
hfxbse/mparty pull request #50
Opened 2023-07-15 12:23 UTC by ubeF

Target Selector used for sabotage and certain action
- Caller can select any player except himself or players with a "sabotage free card"

2023-07-15 13:39 UTC, hfxbse requested changes
Not sure how to test this, as it seems to be not connected to anything right now. Maybe consider it a draft till then?

2023-07-15 13:39 UTC, hfxbse commented on select_target/select_target.gd
> +				var button = preload("res://sabotage_field/target_button.tscn").instantiate()
The file seems to have been moved since writing this.

2023-07-15 13:39 UTC, hfxbse commented on select_target/select_target.gd
> +				$GridContainer.add_child(button)
Nodes from scenes should be selected only once with `@onready` to improve maintainability.

2023-07-15 13:46 UTC, ubeF commented
> Not sure how to test this, as it seems to be not connected to anything right now. Maybe consider it a draft till then?

I tested it in #35  but that branch is still waiting for the implementation in duels and i need the target selector for the action fields. So separated it.

I could merge this branch into action field but i fear it might get ugly

2023-07-16 08:13 UTC, hfxbse approved these changes

2023-07-16 08:16 UTC, hfxbse commented
> > Not sure how to test this, as it seems to be not connected to anything right now. Maybe consider it a draft till then?
> 
> I tested it in #35 but that branch is still waiting for the implementation of duels and i need the target selector for the action fields. So i separated it.
> 
> I could merge this branch into action field but i fear it might get ugly

I guess it is working in #35 but I do not know what the wanted behavior is exactly, so I have to trust you on that one.

The player icons seem to be slightly misaligned to the left, but that is all.

2023-07-16 10:12 UTC, merged